In [1]:
import pandas as pd

In [2]:
path1 = "C:/Code/dtms69/data/AMI/LP_oct2026.parquet"
path2 = "C:/Code/dtms69/data/AMI/LP_nov2026.parquet"
path3 = "C:/Code/dtms69/data/AMI/LP_dec2026.parquet"

In [3]:
df_oct = pd.read_parquet(path1)
df_oct

,PEA_No,KWH,kW average,AA,AB,AC,kW exp average,Finergy,Phase
DATE_Time,,,,,,,,,
2025-10-01 00:00:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
2025-10-01 00:15:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
2025-10-01 00:30:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
2025-10-01 00:45:00,6200022544,0.006,0.024,0.0,0.0,0.0,0.0,false,A
2025-10-01 01:00:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
...,...,...,...,...,...,...,...,...,...
2025-10-31 22:45:00,6200118626,0.002,0.008,0.0,0.0,0.0,0.0,false,A
2025-10-31 23:00:00,6200118626,0.015,0.060,0.0,0.0,0.0,0.0,false,A
2025-10-31 23:15:00,6200118626,0.014,0.056,0.0,0.0,0.0,0.0,false,A
2025-10-31 23:30:00,6200118626,0.014,0.056,0.0,0.0,0.0,0.0,false,A
2025-10-31 23:45:00,6200118626,0.009,0.036,0.0,0.0,0.0,0.0,false,A

In [4]:
df_nov = pd.read_parquet(path2)
df_nov

,PEA_No,KWH,kW average,AA,AB,AC,kW exp average,Finergy,Phase
DATE_Time,,,,,,,,,
2025-11-01 00:00:00,6200022544,0.009,0.036,0.0,0.0,0.0,0.0,false,A
2025-11-01 00:15:00,6200022544,0.008,0.032,0.0,0.0,0.0,0.0,false,A
2025-11-01 00:30:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
2025-11-01 00:45:00,6200022544,0.002,0.008,0.0,0.0,0.0,0.0,false,A
2025-11-01 01:00:00,6200022544,0.002,0.008,0.0,0.0,0.0,0.0,false,A
...,...,...,...,...,...,...,...,...,...
2025-11-30 22:45:00,6200118626,0.014,0.056,0.0,0.0,0.0,0.0,false,A
2025-11-30 23:00:00,6200118626,0.013,0.052,0.0,0.0,0.0,0.0,false,A
2025-11-30 23:15:00,6200118626,0.001,0.004,0.0,0.0,0.0,0.0,false,A
2025-11-30 23:30:00,6200118626,0.001,0.004,0.0,0.0,0.0,0.0,false,A
2025-11-30 23:45:00,6200118626,0.011,0.044,0.0,0.0,0.0,0.0,false,A

In [5]:
df_dec = pd.read_parquet(path3)
df_dec

,PEA_No,KWH,kW average,AA,AB,AC,kW exp average,Finergy,Phase
DATE_Time,,,,,,,,,
2025-12-01 00:00:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
2025-12-01 00:15:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
2025-12-01 00:30:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
2025-12-01 00:45:00,6200022544,0.006,0.024,0.0,0.0,0.0,0.0,false,A
2025-12-01 01:00:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
...,...,...,...,...,...,...,...,...,...
2025-12-31 22:45:00,6200118626,0.008,0.032,0.0,0.0,0.0,0.0,false,A
2025-12-31 23:00:00,6200118626,0.000,0.000,0.0,0.0,0.0,0.0,false,A
2025-12-31 23:15:00,6200118626,0.006,0.024,0.0,0.0,0.0,0.0,false,A
2025-12-31 23:30:00,6200118626,0.014,0.056,0.0,0.0,0.0,0.0,false,A
2025-12-31 23:45:00,6200118626,0.013,0.052,0.0,0.0,0.0,0.0,false,A

In [6]:
df_merge = pd.concat([df_oct, df_nov, df_dec], axis=0)

In [7]:
df_merge

,PEA_No,KWH,kW average,AA,AB,AC,kW exp average,Finergy,Phase
DATE_Time,,,,,,,,,
2025-10-01 00:00:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
2025-10-01 00:15:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
2025-10-01 00:30:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
2025-10-01 00:45:00,6200022544,0.006,0.024,0.0,0.0,0.0,0.0,false,A
2025-10-01 01:00:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,false,A
...,...,...,...,...,...,...,...,...,...
2025-12-31 22:45:00,6200118626,0.008,0.032,0.0,0.0,0.0,0.0,false,A
2025-12-31 23:00:00,6200118626,0.000,0.000,0.0,0.0,0.0,0.0,false,A
2025-12-31 23:15:00,6200118626,0.006,0.024,0.0,0.0,0.0,0.0,false,A
2025-12-31 23:30:00,6200118626,0.014,0.056,0.0,0.0,0.0,0.0,false,A
2025-12-31 23:45:00,6200118626,0.013,0.052,0.0,0.0,0.0,0.0,false,A

In [8]:
df_merge.isna().sum()

PEA_No            0
KWH               0
kW average        0
AA                0
AB                0
AC                0
kW exp average    0
Finergy           0
Phase             0
dtype: int64

In [9]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 173665 entries, 2025-10-01 00:00:00 to 2025-12-31 23:45:00
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PEA_No          173665 non-null  string
 1   KWH             173665 non-null  float64
 2   kW average      173665 non-null  float64
 3   AA              173665 non-null  float64
 4   AB              173665 non-null  float64
 5   AC              173665 non-null  float64
 6   kW exp average  173665 non-null  float64
 7   Finergy         173665 non-null  object
 8   Phase           173665 non-null  object
dtypes: float64(6), object(2), string(1)
memory usage: 13.2+ MB

In [10]:
df_merge.describe()

,KWH,kW average,AA,AB,AC,kW exp average
count,173665.000000,173665.000000,173665.000000,173665.000000,173665.000000,173665.000000
mean,0.137556,0.550225,2.035983,0.000294,0.079400,0.099758
std,0.245809,0.983238,4.682143,0.027253,0.383883,0.362594
min,0.000000,0.000000,-12.000000,0.000000,0.000000,0.000000
25%,0.015000,0.060000,0.000000,0.000000,0.000000,0.000000
50%,0.058000,0.232000,1.000000,0.000000,0.000000,0.000000
75%,0.137000,0.548000,3.000000,0.000000,0.000000,0.000000
max,2.346000,9.384000,42.000000,7.000000,11.000000,2.812000

In [12]:
df_merge['kW_net'] = df_merge['kW average'] - df_merge['kW exp average']

In [13]:
col = df_merge.pop('kW_net')
pos = df_merge.columns.get_loc('kW exp average')
df_merge.insert(pos + 1, 'kW_net', col)

In [14]:
df_merge

,PEA_No,KWH,kW average,AA,AB,AC,kW exp average,kW_net,Finergy,Phase
DATE_Time,,,,,,,,,,
2025-10-01 00:00:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,0.028,false,A
2025-10-01 00:15:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,0.028,false,A
2025-10-01 00:30:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,0.028,false,A
2025-10-01 00:45:00,6200022544,0.006,0.024,0.0,0.0,0.0,0.0,0.024,false,A
2025-10-01 01:00:00,6200022544,0.007,0.028,0.0,0.0,0.0,0.0,0.028,false,A
...,...,...,...,...,...,...,...,...,...,...
2025-12-31 22:45:00,6200118626,0.008,0.032,0.0,0.0,0.0,0.0,0.032,false,A
2025-12-31 23:00:00,6200118626,0.000,0.000,0.0,0.0,0.0,0.0,0.000,false,A
2025-12-31 23:15:00,6200118626,0.006,0.024,0.0,0.0,0.0,0.0,0.024,false,A
2025-12-31 23:30:00,6200118626,0.014,0.056,0.0,0.0,0.0,0.0,0.056,false,A
2025-12-31 23:45:00,6200118626,0.013,0.052,0.0,0.0,0.0,0.0,0.052,false,A

In [15]:
monthly_count = df_merge.groupby(pd.Grouper(freq='M'))['PEA_No'].nunique()

print(monthly_count)

DATE_Time
2025-10-31    20
2025-11-30    20
2025-12-31    19
Freq: ME, Name: PEA_No, dtype: int64

C:\Users\Det_A\AppData\Local\Temp\ipykernel_28204\3201350855.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_count = df_merge.groupby(pd.Grouper(freq='M'))['PEA_No'].nunique()

In [22]:
monthly_pea = df_merge.groupby(pd.Grouper(freq='ME'))['PEA_No'].unique()

print(monthly_pea.to_string())

DATE_Time
2025-10-31    [6200022544, 6200030933, 6200031047, 620003105...
2025-11-30    [6200022544, 6200030933, 6200031047, 620003105...
2025-12-31    [6200022544, 6200030933, 6200031047, 620003105...
Freq: ME

In [25]:
oct = set(df_merge[df_merge.index.month == 10]['PEA_No'].unique())
dec = set(df_merge[df_merge.index.month == 12]['PEA_No'].unique())

# มีใน Jan แต่ไม่มีใน Feb
missing_pea = oct - dec

print("Missing:", missing_pea)

Missing: {'6200031084'}

In [26]:
output_path = "E:/Documents/dtms69/merge_LP_2026.parquet"

In [27]:
df_merge.to_parquet(output_path, engine='pyarrow', index=True)